spring:
  data:
    mongodb:
      database: codesprint
      uri: mongodb://localhost:27017/codesprint
  ai:
    openai:
      api-key: ${OPENAI_API_KEY} # Still recommended to use an environment variable for security

server:
#  address: 0.0.0.0
  port: 8085

whatsapp:
  token: EAAVVXi87S6wBPBPTcx7Kxcpxjeo08HvO62mYj80qvTwU8vVjQyqZBQTdtgWF1ThQcBew9x2BxKaBZC7rxvBkx9ZAyCAX6osO6eZChIrjiyXXpBR1jQE9JmJZC55ZCiTEWi3ffgWsk0ISKzlYOvkxKbmAt92up9ze4SHvi2gdHIrM6eZC7s3NseW5So5Xh5068oUvWD9l1AFZAqX227iziJZBkl7S28nWJoUXAdUk3mwaKKJUDaLoZD
  to: 35679820028 # enter phone number recipient and make sure to include in whatsapp business api
  accountId: 669393152930636

alert:
  loss:
    threshold: 100.00  # Only alert if loss exceeds $100
  enabled: true        # Enable/disable all alerts
