spring:
  data:
    mongodb:
      database: codesprint
      uri: mongodb://localhost:27017/codesprint
  ai:
    openai:
      api-key: ${OPENAI_API_KEY} # Still recommended to use an environment variable for security

server:
#  address: 0.0.0.0
  port: 8085

whatsapp:
  token:
  to:  # enter phone number recipient and make sure to include in whatsapp business api
  accountId:

alert:
  loss:
    threshold: 100.00  # Only alert if loss exceeds $100
  enabled: true        # Enable/disable all alerts
